[package]
edition = "2021"
name = "tinyrust"
version = "0.1.0"

[dependencies]
color-eyre = "0.5.11"
eyre = "0.6.5"
lazy_static = "1.4.0"
regex = "1.5.4"
tracing = "0.1.29"
tracing-error = "0.1.2"
tracing-subscriber = "0.2.25"
