[package]
edition = "2021"
name = "ckc"
version = "0.1.0"

[dependencies]
GSL = "6.0.0"
bitvec = "0.22.3"
color-eyre = "0.5.11"
rayon = "1.5.1"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.68"
sha-1 = "0.9.8"
statrs = "0.15.0"
tinyvm = {path = "../tinyvm"}
